openapi: 3.0.3
info:
  title: Yemek Kapımda API
  version: 1.0.0
  description: >
    Bu API, kullanıcların sitemizde bulunan restoranları istediği yemek kategorisine göre veya sipariş vermek
    istediği restoranları arama yaparak bunları yıldızına göre sıralama veya kategorilerine göre filtreleme 
    yaparak yemek siparişi verebileceği bir RESTful servistir. CRUD (Create,Read,Update,Delete) işlemlerini destekler.
    API, JWT Tabanlı kimlik doğrulama ile korunmaktadır.
  contact:
    name: Muhammet Dursun
    email: muhammettdrsn@gmail.com

servers:
  - url: https://api.vercel.com
    description: Üretim sunucusu (Production)
  - url: https://staging-api.vercel.com
    description: Test sunucusu (Staging)
  - url: http://localhost:3000
    description: Yerel geliştirme sunucusu (Development)

tags:
  - name: Kimlik
    description: Kullanıcı kayıt olma, giriş, çıkış işlemleri
  - name: Restoran
    description: Restoran sıralama, listeleme, filtreleme, yıldız verme
  - name: Profil
    description: Profilini görüntüleme, bilgileri güncelleme
  - name: Adres
    description: Adresini ekleme, görüntüleme, güncelleme, silme
    
security:
  - BearerAuth: []

paths: 
  /auth/register:
    post:
      tags:
        - Kimlik
      summary: Üye Ol
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: Kullanıcı başarıyla kayıt oldu
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Geçersiz bilgiler
        '409':
          description: Bu email zaten kayıtlı
  
  /auth/login:
    post:
      tags: 
        - Kimlik
      summary: Giriş Yap
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
      responses:
        '200':
          description: Kullanıcı girişi yapıldı.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Email ve şifre boş bırakılamaz.
        '401':
          description: Email veya şifre geçersiz.

  /account/profile/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        description: Kullanıcının benzersiz kimlik numarası
        schema:
          type: integer
        example: 1
        
    get:
      tags: 
        - Profil
      summary: Kullanıcının profilini getir
      operationId: getProfileByUserId
      responses:
        '200':
          description: Profil başarıyla getirildi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Girilen id geçersiz
        '404':
          description: Kullanıcı bulunamadı

    put:
      tags: 
        - Profil
      summary: Kullanıcının profil bilgilerini güncelle
      operationId: updateProfileById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '200':
          description: Profil bilgileri başarıyla güncellendi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Girilen id geçersiz
        '401':
          description: Kimlik doğrulama başarısız
        '403':
          description: Bu işlem için yetkiniz geçersiz
        '404':
          description: Kullanıcı bulunamadı

  /account/address:
    post:
      tags: 
        - Adres
      summary: Hesaba adres ekle
      operationId: createAddress
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAddressRequest'
      responses:
        '201':
          description: Adres eklendi.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Adres'
        '400':
          description: Geçersiz adres bilgileri
        '401':
          description: Önce giriş yapmalısın
        '403':
          description: Bu işlem için yetkiniz yetersiz.
      
  /account/address/{addressId}:
    parameters:
      - name: addressId
        in: path
        required: true
        description: Adresin benzersiz kimlik numarası
        schema:
          type: number
          format: long
        example: 1  

    put:
      tags: 
        - Adres
      summary: Adres bilgilerini güncelle
      operationId: updateAddressById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAddressRequest'
      responses:
        '200':
          description: Adres bilgileri güncellendi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Adres'
        '400':
          description: Adres bilgilerin geçersiz
        '401':
          description: Kimlik doğrulaması geçersiz
        '403':
          description: Bu işlem için yetkiniz bulunmuyor
        '404':
          description: Adres bulunamadı

    delete:
      tags: 
        - Adres
      summary: Adresi Sil
      operationId: deleteAddress
      responses:
        '204':
          description: Adres başarıyla silindi
        '401':
          description: Kimlik doğrulama başarısız
        '403':
          description: Bu işlem için yetkiniz bulunmuyor
        '404':
          description: Adres bulunamadı

  /restaurant:
    get:
      tags: 
        - Restoran
      summary: Restoranları getir, sırala ve filtrele
      operationId: getRestorans
      parameters:
        - name: sort
          in: query
          required: false
          description: Restoranları sıralamak için kullanılır. Yıldızlara göre sıralamak için 'stars' gönderin.
          schema:
            type: string
            enum: 
              - stars
          example: "stars"
        - name: cuisine
          in: query
          required: false
          description: Mutfak türüne göre filtrelemek için 'cuisine' gönderin.
          schema:
            type: string
          example: "Pizza"
        - name: name
          in: query
          required: false
          description: Restoran isimlerinde arama yapmak için kullanılır.
          schema:
            type: string
          example: "Kebap Evi"
      responses:
        '200':
          description: Restoranlar başarıyla getirildi
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restoran'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'JWT tabanlı kimlik doğrulama.'

  schemas:
    User:
      type: object
      description: Kullanıcıları temsil eden model
      properties:
        userId:
          type: integer
          description: Kullanıcıların benzersiz kimlik numarası (otomatik olarak atanır)
          example: 1
        name:
          type: string
          description: Kullanıcıların ismi
          example: "Ali"
        surname:
          type: string
          description: Kullanıcıların soyismi
          example: "Yılmaz"
        email:
          type: string
          description: Kullanıcıların email adresi
          example: "aliyilmaz@gmail.com"

    Restoran:
      type: object
      description: Restoranları temsil eden model
      properties:
        restaurantId:
          type: integer
          description: Restoranların benzersiz kimlik numarası (otomatik olarak atanır)
          example: 2
        name:
          type: string
          description: Restoranların ismi
          example: "Pizza Dünyası"
        stars:
          type: number
          format: float
          description: Restoranların yıldız puanı
          example: 4.4
        cuisine:
          type: string
          description: Restoranların mutfak türü
          example: "Izgara"
      
    Adres:
      type: object
      description: Adresi temsil eden model
      properties:
        addresId:
          type: integer
          description: Adresin benzersiz kimlik numarası (otomatik olarak atanır)
          example: 2
        addressTitle:
          type: string
          description: Adresin ev veya iş adresi olduğunu belirtir
          example: "Ev Adresi"
        city:
          type: string
          description: Adresin bulunduğu il
          example: "Isparta"
        district:
          type: string
          description: Adresin bulunduğu ilçe
          example: "Merkez"
        fullAddress:
          type: string
          description: Adresin bulunduğu ek bilgiler mahalle,sokak,bina ismi no
          example: "Bahçelievler Mahallesi 3000 Sokak"

    CreateUserRequest:
      type: object
      description: Kullanıcı kayıt olmak için gönderilecek veri
      properties:
        name:
          type: string
          description: Kullanıcıların ismi
          example: "Ali"
        surname:
          type: string
          description: Kullanıcıların soyismi
          example: "Yılmaz"
        email:
          type: string
          description: Kullanıcıların email adresi
          example: "aliyilmaz@gmail.com"
        password:
          type: string
          description: Kullanıcıların şifresi
          example: "ali123"
      required:
        - name
        - surname
        - email
        - password

    LoginUserRequest:
      type: object
      description: Kullanıcı giriş yapmak için göndereceği veri
      properties:
        email:
          type: string
          description: Kullanıcıların email adresi
          example: "aliyilmaz@gmail.com"
        password:
          type: string
          description: Kullanıcıların şifresi
          example: "ali123"
      required:
        - email
        - password

    CreateAddressRequest:
      type: object
      description: Adres oluşturmak için gönderilecek veri
      properties:
        addressTitle:
          type: string
          description: Adresin ev veya iş adresi olduğunu belirtir
          example: "Ev Adresi"
        city:
          type: string
          description: Adresin bulunduğu il
          example: "Isparta"
        district:
          type: string
          description: Adresin bulunduğu ilçe
          example: "Merkez"
        fullAddress:
          type: string
          description: Adresin bulunduğu ek bilgiler mahalle,sokak,bina ismi no
          example: "Bahçelievler Mahallesi 3000 Sokak"
      required:
        - addressTitle
        - city
        - district
        - fullAddress

    UpdateAddressRequest:
      type: object
      description: Adres güncellemek için gönderilecek veri
      properties:
        addressTitle:
          type: string
          description: Adresin ev veya iş adresi olduğunu belirtir
          example: "Ev Adresi"
        city:
          type: string
          description: Adresin bulunduğu il
          example: "Isparta"
        district:
          type: string
          description: Adresin bulunduğu ilçe
          example: "Merkez"
        fullAddress:
          type: string
          description: Adresin bulunduğu ek bilgiler mahalle,sokak,bina ismi no
          example: "Bahçelievler Mahallesi 3000 Sokak"
