pipeline {
    agent any

    environment {
        APP_NAME = "yemek-kapimda-backend"
        PORT = "8081"
    }

    stages {
        stage('1. Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('2. Build Docker Image') {
            steps {
                dir('yemek-kapimda') {
                    sh "docker build -t ${APP_NAME}:latest ."
                }
            }
        }

        stage('3. Deploy (Konteyneri Ayağa Kaldır)') {
            steps {
                dir('yemek-kapimda') {

                    sh "docker rm -f ${APP_NAME} || true"


                    sh "docker run -d -p ${PORT}:8080 --name ${APP_NAME} ${APP_NAME}:latest"
                }
            }
        }
    }
}