pipeline {
    agent any

    environment {
        APP_NAME = "yemek-kapimda-backend"
        // Jenkins 8080'i kullandığı için çakışmayı önlemek adına 8081 yapıyoruz
        PORT = "8081"
    }

    stages {
        stage('1. Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('2. Build Docker Image') {
            steps {
                dir('yemek-kapimda') {
                    sh "docker build -t ${APP_NAME}:latest ."
                }
            }
        }

        stage('3. Deploy (Konteyneri Ayağa Kaldır)') {
            steps {
                dir('yemek-kapimda') {
                    // -f (force) parametresi ile takılı kalan konteynerleri zorla siliyoruz
                    sh "docker rm -f ${APP_NAME} || true"

                    // Yeni port ayarıyla konteyneri başlatıyoruz
                    sh "docker run -d -p ${PORT}:8080 --name ${APP_NAME} ${APP_NAME}:latest"
                }
            }
        }
    }
}