spring:
  application:
    name: yemek-kapimda
  datasource:
    url: jdbc:postgresql://ep-curly-forest-alw2pr0n.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: npg_VQtORbiL5gf4
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    uris: https://6b8ec2ce32:08b3b74616e338743ebe@elasticsearch-1njrv7e9.us-east-1.bonsaisearch.net
    connection-timeout: 10s
    socket-timeout: 30s

app:
  jwt:
    secret: ${JWT_SECRET:fxePspkTDCUT0XkOKeQpWPP13lOmRIMTaIAN5M4QM0j}
    expiration-ms: 1209600000
